name: TreeManagerPlugin
version: 1.0.0
main: com.trees.TreeManagerPlugin
api-version: "1.19"
depend: [WorldGuard]
softdepend: [PlaceholderAPI]
description: Zone-based tree farms with different permission levels and customizable messages
author: Pope

commands:
  treemanager:
    description: Manage TreeManager plugin
    usage: /<command> reload
    permission: treemanager.reload

permissions:
  treemanager.reload:
    description: Reload TreeManager configuration
    default: op
  treefarm.basic:
    description: Access to basic tree farms
    default: false
  treefarm.premium:
    description: Access to premium tree farms
    default: false
  treefarm.vip:
    description: Access to VIP tree farms
    default: false